
# .github/workflows/zarbakht-scan.yml 

name: Zarbakht-Scan 

on: 
  push: 
    branches:
      - '*' 
    workflow_dispatch:

jobs: 
  armourzero_security_test_pre: 
    runs-on: ubuntu-latest 

    env:
    AZ_API_KEY: "${{ secrets.AZ_TOKEN }}" 
    PROJECT_KEY: "FzhbNnXTzmTeJIQGeDTDXnIppfXCbpRf" 
    BRANCH_NAME: "${{ github.ref_name }}"

    steps: 
    - name: Checkout Repository 
    uses: actions/checkout@v2 

    - name: ArmourZero Security Test (Pre) 
    run: | 
      docker run -v "$(pwd):/app/wrk" --rm armourzero/pipe-scan:latest --apikey="$AZ_API_KEY" --projectkey="$PROJECT_KEY" --branch="$BRANCH_NAME" --repo="$GITHUB_REPOSITORY" 
  continue-on-error: true
